# -*- coding: utf-8 -*-
"""FUNDAMENTOS DA PROGRAMAÇÃO COM PYTHON.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LpP8GoIrqVh1cEG6x5LY5ItvDAnsZqTB
"""

print ("frase de cima")

print ("frase de cima", end = ' ')
print ("frase de baixo")

print ("frase de cima")
print ("frase de baixo")

print ("BEM-VINDO!")

Nome = input ('Digie o seu nome: ')
print(f'BEM VINDO: {Nome}!')

n1 = int(input('Entre com o primeiro número: '))
n2 = int(input('Entre com o segundo número: '))
print (f'Soma = {n1+n2}')

nome = "João"
idade = 25

# Usando f-string para formatar a string
mensagem = f"Olá, meu nome é {nome} e eu tenho {idade} anos."

print(mensagem)

"""As f-strings são indicadas pelo prefixo 'f' antes das aspas que delimitam a string e permitem que você insira variáveis, expressões e formatação diretamente dentro das chaves {} dentro da string."""

produto = "bicicleta"
preco = 350.50
quantidade = 4

# Usando f-string para formatar a string
fatura = f"Você comprou {quantidade} {produto}s por um total de R${preco * quantidade:.2f}."

print(fatura)

"""A expressão {preco * quantidade:.2f} calcula o preço total (multiplicação do preço pela quantidade) e, em seguida, formata esse valor como um número de ponto flutuante com duas casas decimais. Isso garante que o preço total seja exibido com precisão até os centavos.

- f indica que é uma formatação de ponto flutuante.
- .2 especifica o número de casas decimais que devem ser exibidas após o ponto decimal. Neste caso, 2 significa que queremos mostrar duas casas decimais.
"""

# como printar cada letra de um nome
p = 'Derek'
print(p)
print(p[0],p[1],p[2],p[3],p[4],sep = '-')

# como printar uma lista, neste caso um elemento de uma lista

coisas = ['x', 1, 'teste', 3.14, True]
print(coisas[4], coisas[2])

